apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: strts2ordermanager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: strts2ordermanager
  project: "default"
  syncPolicy:   
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  source:
    path: dev
    repoURL: https://github.com/blcporgs/struts2ordermanagerdeployments.git
