apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: rest-angular
  name: rest-angular
spec:
  clusterIP: None
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
  selector:
    move2kube.konveyor.io/service: rest-angular
  type: ClusterIP
status:
  loadBalancer: {}
